### ISSUE TITLE
FacebookSocialNetwork.requestPostMessage NPE

### ISSUE THREAD

**Issue by devindi** [gorbin/ASNE#102]
Trying next code
```java
socialNetworkManager.getSocialNetwork(FacebookSocialNetwork.ID).requestPostMessage("Message!")
```

and got 
```php
FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference
    at com.facebook.Session$AuthorizationRequest$1.startActivityForResult(Session.java:1902)
    at com.facebook.Session.tryLoginActivity(Session.java:1409)
    at com.facebook.Session.authorize(Session.java:1159)
    at com.facebook.Session.requestNewPermissions(Session.java:1264)
    at com.facebook.Session.requestNewPublishPermissions(Session.java:595)
    at com.github.gorbin.asne.facebook.FacebookSocialNetwork.performPublish(FacebookSocialNetwork.java:441)
    at com.github.gorbin.asne.facebook.FacebookSocialNetwork.requestPostMessage(FacebookSocialNetwork.java:341)
    at com.myapp.fragment.share.ShareFragment$onViewCreated$1.onClick(ShareFragment.java:56)
    at android.view.View.performClick(View.java:5184)
    at android.view.View$PerformClick.run(View.java:20910)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5942)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

Login via facebook passed OK. FB scope is "public_profile, email, user_friends, user_location, user_birthday"

**Comment by devindi** [comment]
I used requestPostLink instead of requestPostMessage and all is ok.
