### ISSUE TITLE
NullPointerException in SocialNetwork.<init>

### ISSUE THREAD

**Issue by dunknown** [gorbin/ASNE#52]
I get a NullPoineterEcxeption when I try to instantiate a SocialNetwork.

```
VkSocialNetwork vk = new VkSocialNetwork(new Fragment(), VK_APP_ID, vkScope);
```

```
 java.lang.NullPointerException
            at com.github.gorbin.asne.core.SocialNetwork.<init>(SocialNetwork.java:127)
            at com.github.gorbin.asne.vk.VkSocialNetwork.<init>(VkSocialNetwork.java:142)
```

Since I don't use any fragments in my app, I've created a separate class for working with ASNE, so I can't pass "this" as first parameter (like in your tutorial) and I've decided to just create a new Fragment. But it doesn't seem to work. I've also tried passing mSocialNetworkManager fragment as first parameter and got the same exception.

**Comment by r3dh4nd5** [comment]
Any progress on this, possible workaround?
