### ISSUE TITLE
when try to get fb friends

### ISSUE THREAD

**Issue by vazeer** [gorbin/ASNE#55]
java.lang.NullPointerException
            at com.github.gorbin.asne.facebook.FacebookSocialNetwork$5.onCompleted(FacebookSocialNetwork.java:510)
            at com.facebook.Request$2.onCompleted(Request.java:302)
            at com.facebook.Request$4.run(Request.java:1666)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5139)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by gentra** [comment]
Is this fixed? Or is there any workaround for this?
