### ISSUE TITLE
NPE at com.vk.sdk.VKSdk.isLoggedIn() at com.github.gorbin.asne.vk.VkSocialNetwork.isConnected()

### ISSUE THREAD

**Issue by dunknown** [gorbin/ASNE#58]
I get a NullPointerException when calling VkSocialNetwork.isConnected()

```
java.lang.NullPointerException: Attempt to read from field 'com.vk.sdk.VKAccessToken com.vk.sdk.VKSdk.mAccessToken' on a null object reference
            at com.vk.sdk.VKSdk.isLoggedIn(VKSdk.java:405)
            at com.github.gorbin.asne.vk.VkSocialNetwork.isConnected(VkSocialNetwork.java:192)
            ...
```

**Comment by eugene-polyakov** [comment]
Might be too late, but i just hit the same problem - make sure that
                getFragmentManager().beginTransaction().add(mSocialNetworkManager, MainActivity.SOCIAL_NETWORK_TAG).commit();
is called in your fragment
