### ISSUE TITLE
Could not find matching constructor for: com.github.gorbin.asne.facebook.FacebookSocialNetwork

### ISSUE THREAD

**Issue by woshibt** [gorbin/ASNE#86]
Error:

05-06 23:50:29.967  26722-26722/me.android.MyApp D/KF BugReportService﹕ java.lang.RuntimeException: Unable to start activity ComponentInfo{me.android.MyApp/me.android.MyApp.activities.LoginActivity}: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.github.gorbin.asne.facebook.FacebookSocialNetwork(me.android.MyApp.activities.LoginMethodFragment, java.util.ArrayList)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.github.gorbin.asne.facebook.FacebookSocialNetwork(me.android.MyApp.activities.LoginMethodFragment, java.util.ArrayList)
            at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1723)
            at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1526)
            at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:252)
            at me.android.MyApp.activities.LoginMethodFragment.onCreateView(LoginMethodFragment.groovy:139)
            at android.app.Fragment.performCreateView(Fragment.java:2053)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:834)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.Activity.performStart(Activity.java:6005)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Code:

public class LoginMethodFragment extends Fragment implements SocialNetworkManager.OnInitializationCompleteListener, OnLoginCompleteListener {
    public static SocialNetworkManager mSocialNetworkManager;

    public static final String TAG = "KF LoginMethodFragment"
    private FragmentActivity fragmentActivity;
......

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState){
        View view = inflater.inflate(R.layout.fragment_login_method, container, false);

        //Chose permissions
        ArrayList<String> fbScope = new ArrayList<String>();
        fbScope.addAll(Arrays.asList("public_profile, email, user_friends"));

        //Use manager to manage SocialNetworks
        mSocialNetworkManager = (SocialNetworkManager) getFragmentManager().findFragmentByTag(LoginActivity.SOCIAL_NETWORK_TAG);

        //Check if manager exist
        if (mSocialNetworkManager == null) {
            mSocialNetworkManager = new SocialNetworkManager();

            //Init and add to manager FacebookSocialNetwork
            FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(this, fbScope);
            mSocialNetworkManager.addSocialNetwork(fbNetwork);

            //Initiate every network from mSocialNetworkManager
            getFragmentManager().beginTransaction().add(mSocialNetworkManager, LoginActivity.SOCIAL_NETWORK_TAG).commit();
            mSocialNetworkManager.setOnInitializationCompleteListener(this);
        } else {
            //if manager exist - get and setup login only for initialized SocialNetworks
            if(!mSocialNetworkManager.getInitializedSocialNetworks().isEmpty()) {
                List<SocialNetwork> socialNetworks = mSocialNetworkManager.getInitializedSocialNetworks();
                for (SocialNetwork socialNetwork : socialNetworks) {
                    socialNetwork.setOnLoginCompleteListener(this);
                    initSocialNetwork(socialNetwork);
                }
            }
        }
        return view;
    }

**Comment by mghildiy** [comment]
Hi,
I am trying to implement linkedin login functionality. So I do following in my fragment class:

LinkedInSocialNetwork liNetwork = new LinkedInSocialNetwork(this, LINKEDIN_CLIENT_KEY, LINKEDIN_CLIENT_SECRET,
                LINKEDIN_CALLBACK_URL, linkedInScope);

But my fragment class extends android.app.Fragment while LinkedInSocialNetwork's constructor  takes  android.support.v4.app.Fragment, hence code doesn't compile.

How to work around this issue?

With regards
Manish
