### ISSUE TITLE
com.github.gorbin.asne.core.SocialNetworkException: Social network with id = 4 not found

### ISSUE THREAD

**Issue by uness** [gorbin/ASNE#89]
When i try to call mSocialNetworkManager.getSocialNetwork(networkId) (after init and added a social network) i get the error below : 

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    com.github.gorbin.asne.core.SocialNetworkException: Social network with id = 4 not found
            at com.github.gorbin.asne.core.SocialNetworkManager.getSocialNetwork(SocialNetworkManager.java:159)
            at com.myapp.fragments.SocialNetFragment$6.onClick(SignInFragment_.java:307)
            at com.facebook.widget.LoginButton$LoginClickListener.onClick(LoginButton.java:870)
            at android.view.View.performClick(View.java:4232)
            at android.view.View$PerformClick.run(View.java:17298)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by sagar23jan** [comment]
@uness were you able to resolve the issue ? I am facing the same problem and it appears randomly.

**Comment by askarsyzdykov** [comment]
Google+
com.github.gorbin.asne.core.SocialNetworkException: Social network with id = 3 not found
       at com.github.gorbin.asne.core.SocialNetworkManager.getSocialNetwork(SocialNetworkManager.java:159)

**Comment by Lawliet666** [comment]
GooglePlusSocialNetwork googleNetwork = new GooglePlusSocialNetwork(fragment);// for id = 3
mSocialNetworkManager.addSocialNetwork(googleNetwork); 

FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(fragment, fbScope); // for id = 4
            mSocialNetworkManager.addSocialNetwork(fbNetwork);

Add social network before call getSocialNetwork()
