### ISSUE TITLE
NullPointerException after calling requestCurrentPerson()

### ISSUE THREAD

**Issue by mifa** [gorbin/ASNE#93]
```javascript
java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.gorbin.asne.core.listener.OnRequestSocialPersonCompleteListener.onRequestSocialPersonSuccess(int, com.github.gorbin.asne.core.persons.SocialPerson)' on a null object reference
            at com.github.gorbin.asne.vk.VkSocialNetwork$3.onComplete(VkSocialNetwork.java:290)
            at com.vk.sdk.api.VKRequest$3.run(VKRequest.java:459)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by mifa** [comment]
This happens after second login to VK, only reinstalling helps.

**Comment by Firsto** [comment]
How to repeat it?
I saw that log at crash reports, and can't understand how they cause it
