### ISSUE TITLE
NoClassDefFoundError: @ FacebookSocialNetwork class

### ISSUE THREAD

**Issue by anvesh523** [gorbin/ASNE#98]
FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(this, fbScope);

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.github.gorbin.asne.facebook.FacebookSocialNetwork$1
            at com.github.gorbin.asne.facebook.FacebookSocialNetwork.<init>(FacebookSocialNetwork.java:87)
            at a2a.example.testapp.MainFragment.onCreateView(MainFragment.java:75)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1016)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1197)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:511)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1167)
            at android.app.Activity.performStart(Activity.java:5192)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
            at android.app.ActivityThread.access$600(ActivityThread.java:156)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5299)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wahidstephen** [comment]
Even I have the same error. Help? Anyone?

**Comment by dilix** [comment]
It happens when you try add newer facebook sdk for android and use ASNE same time.
ASNE uses
`private Session.StatusCallback`

And Session like many other classes are not available in facebook sdk 4+.
